vim.cmd [[autocmd FileType python nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="python %"<CR>]]
vim.cmd [[autocmd FileType sh nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="bash %"<CR>]]
vim.cmd [[autocmd FileType tex nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="pdflatex %"<CR>]]
vim.cmd [[autocmd FileType javascript nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="node %"<CR>]]
vim.cmd [[autocmd FileType cpp nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="g++ % && ./a.out"<CR>]]
vim.cmd [[autocmd FileType c nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="gcc % && ./a.out"<CR>]]
vim.cmd [[autocmd FileType go nnoremap <buffer> <leader><CR> :w<CR>:TermExec cmd="go build % && ./main"<CR>]]
vim.cmd [[autocmd FileType sql nnoremap <buffer> <leader><CR> :w<CR>:SqlsExecuteQueryVertical<CR>]]
vim.cmd [[autocmd FileType yaml.ansible nnoremap <buffer> <leader><CR> :w<CR>:lua require('ansible').run()<CR>]]
vim.cmd [[autocmd FileType lua nnoremap <buffer> <leader><CR> :w<CR>:!lua %<CR>]]
